### ISSUE TITLE
版本问题

### ISSUE THREAD

**Issue by joyboyzy** [Layui-WPF-Team/Layui-WPF#13]
挺喜欢的，之前的layui 就停更了，加油！。
这个版本是.net framework 4.5.2, 以后发布nuget包的时候可以适应高版本么，似乎是个问题耶，兄弟！ 
请坚持下去，看好你哟。

**Comment by Coolkeke** [comment]
core是兼容framework 不需要担心兼容问题 我的版最低兼容framework 4.5.2 只要不低于这个基本上没什么问题

**Comment by Coolkeke** [comment]
项目上线会发布高版本 目前测试开发阶段就是以framework 4.5.2开发

**Comment by fengbol** [comment]
> 挺喜欢的，之前的layui 就停更了，加油！。 这个版本是.net framework 4.5.2, 以后发布nuget包的时候可以适应高版本么，似乎是个问题耶，兄弟！ 请坚持下去，看好你哟。

layui 没停更啊

**Comment by Coolkeke** [comment]
已更新至最高版本net7.0支持
