### ISSUE TITLE
说明文档有写吗，这么好的项目，没有相关文档可惜了。

### ISSUE THREAD

**Issue by shidaizhou** [Layui-WPF-Team/Layui-WPF#14]

**Comment by shidaizhou** [comment]
都没文档说明怎么接入到 其他wpf的项目中

**Comment by Coolkeke** [comment]
目前还在开发中，使用文档会在发第一版的Nuget包的时候一起上线

**Comment by shidaizhou** [comment]
期待你的项目正式上线，可以先不用很全的功能，早点上线后面再迭代更好。

**Comment by shidaizhou** [comment]
> 目前还在开发中，使用文档会在发第一版的Nuget包的时候一起上线
预计什么时间 上线呢

**Comment by Coolkeke** [comment]
目前该项目所有代码都是我多余时间一人开发 不是全职开发这个库 发布可能没那么快 有些基础控件都没去修改调整 考虑到只要发包了 就一定会有人去用这个  可能会出现控件使用问题 就没去发版 上线时间的话 今年一定可以发出去一版本 具体的发布时间 我会以视频的方式公告 目前使用的话 你们就暂时那这源代码开发 我里面备注和样例也写的很清晰 学习期来不会很难

**Comment by Coolkeke** [comment]
目前该项目所有代码都是我多余时间一人开发 不是全职开发这个库 发布可能没那么快 有些基础控件都没去修改调整 考虑到只要发包了 就一定会有人去用这个 可能会出现控件使用问题 就没去发版 上线时间的话 今年一定可以发出去一版本 具体的发布时间 我会以视频的方式公告 目前使用的话 你们就暂时拿这源代码开发 我里面备注和样例也写的很清晰 学习起来不会很难

**Comment by Coolkeke** [comment]
文档正在搭建，文档地址，目前已确定，一切项目源码为准，网站文档存在更新不及时问题
[在线学习地址](https://layui-wpf-team.github.io/Document/)
