### ISSUE TITLE
Keyboard 无法手动隐藏一些系统按键，如Win键，还有Keyboard控件无法同时按住Ctrl+其它建

### ISSUE THREAD

**Issue by DrZhong** [Layui-WPF-Team/Layui-WPF#15]
如题，如何使用虚拟键盘敲出数字键上的符号呢，需要按住Shift键再按数字键，这个键盘好像无法实现

**Comment by DrZhong** [comment]
可以参考win11虚拟键盘的设计，点一下Shift键以后 Shift建会常亮，然后再点其它键，就会组合触发 Shift+其他键

**Comment by Coolkeke** [comment]
> 如题，如何使用虚拟键盘敲出数字键上的符号呢，需要按住Shift键再按数字键，这个键盘好像无法实现

可以实现的，我这边还没去考虑那么多，期初是想完成一下基础的效果，现在核心功能完成了，你说的这个事比较好实现的，如果是想要一直输入字符或者数字的我这边要在键盘里面记录一下状态就好了，我这段时间比较忙，空闲下来了，我就开始针对控件以及其他的一些使用体验上进行调整

**Comment by Coolkeke** [comment]
键盘功能已完成，可以看一下最新代码
