### ISSUE TITLE
怎么不持续更新了呢？

### ISSUE THREAD

**Issue by LiuChao19940201** [Layui-WPF-Team/Layui-WPF#17]
怎么没有持续更新了呢？说好的正式发布的版本呢？现在还是只有预览版的，up加油，这么好的项目别埋没了。。。。

**Comment by Coolkeke** [comment]
马上开始更新代码了，最近有点事很多东西都停止下来了

**Comment by Coolkeke** [comment]
最近有推送新包，源码也有更新，新增了许多控件可以尝鲜，过段时间就看到无需新增必须使用的控件了就开始发布正式版本包
