### ISSUE TITLE
鼠标移上信息提示过长时超出窗体

### ISSUE THREAD

**Issue by bjlualy** [Layui-WPF-Team/Layui-WPF#20]
是否可以支持提示内容自动换行，和手动换行？
有时候当提示内容过多时会超出窗体，有的提示内容是需要自己来分行显示的，辛苦群主添加此功能。

**Comment by flamegreat** [comment]
自动换行可以用TextBlock ：<TextBlock TextWrapping="Wrap">这是一段需要换行的文本。</TextBlock>
手动换行可以这么写：第一行文本&#x0a;第二行文本。   &#x0a; 就是换行的意思

**Comment by flamegreat** [comment]
自动换行使用示例：
`        <lay:LayToolTip
            Margin="20"
            Placement="Top">
            <lay:LayToolTip.ToolTipContent>
                <TextBlock Width="100" TextWrapping="Wrap">这是一段会自动换行的文本字符串</TextBlock>
            </lay:LayToolTip.ToolTipContent>
            <lay:LayButton Content="向上" />
        </lay:LayToolTip>`

**Comment by flamegreat** [comment]
手动换行使用示例：
`        <lay:LayToolTip
            Margin="20"
            Placement="Top"
            ToolTipContent="手动换行示例&#x0a;这是提示信息">
            <lay:LayButton Content="向上" />
        </lay:LayToolTip>`
