### ISSUE TITLE
选项按钮不能设置宽高

### ISSUE THREAD

**Issue by bjlualy** [Layui-WPF-Team/Layui-WPF#21]
![微信截图_20240509183250](https://github.com/Layui-WPF-Team/Layui-WPF/assets/6881924/c191cd52-6527-4507-b9a8-91c4c8999c8e)
这个选项按钮是否可以支持设置宽和高的属性。

**Comment by flamegreat** [comment]
可以设置高度，宽度会根据高度自适应

**Comment by Coolkeke** [comment]
我在考虑是不是需要放宽内部小方块的形状显示设置限制，现在没有很好地理由想法支持我去调整这个
