### ISSUE TITLE
不能启动

### ISSUE THREAD

**Issue by gugupda** [Layui-WPF-Team/Layui-WPF#24]
main branch不能正常启动
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	CS0234	The type or namespace name 'PropertyGrid' does not exist in the namespace 'LayuiComponentExample.Views' (are you missing an assembly reference?)	LayuiComponentExample	C:\VS_projs\Layui-WPF-main\src\LayuiPack\Models\LayuiComponentExample\LayuiComponentExampleModule.cs	43

**Comment by Coolkeke** [comment]
方便提供一下工程源码吗，我这边没发现这样的问题，学习我这个项目的相关人也没发现中问题，目前为止没有说启动不了的，这个会不是你环境有点问题呀

**Comment by gugupda** [comment]
还没用到工程中，下载的源码直接启动的，main branch发生问题，release branch可以正常启动




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Layui-WPF-Team/Layui-WPF"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月18日(星期二) 下午4:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Layui-WPF-Team/Layui-WPF] 不能启动 (Issue #24)





 
方便提供一下工程源码吗，我这边没发现这样的问题，学习我这个项目的相关人也没发现中问题，目前为止没有说启动不了的，这个会不是你环境有点问题呀
