### ISSUE TITLE
LayGroupBox

### ISSUE THREAD

**Issue by ms1094392787** [Layui-WPF-Team/Layui-WPF#30]
LayGroupBox 没有加 padding 属性,  导致 LayGroupBox的header 和内容会重合在一起

**Comment by ms1094392787** [comment]
边框没有包住内容.
![image](https://github.com/user-attachments/assets/0e8945aa-c053-4c38-bab1-57f34f0ba616)

**Comment by Coolkeke** [comment]
已修复
